In [25]:
import pandas as pd 
import numpy as np 

In [26]:
dataset = pd.read_csv(r'Crop_recommendation.csv')
X= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
dataset.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [27]:
missing_values_per_column = dataset.isnull().sum()
total_missing_values = dataset.isnull().sum().sum()
print("Missing values per column:")
print(missing_values_per_column)
print("\nTotal missing values in the DataFrame:")
print(total_missing_values)

Missing values per column:
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

Total missing values in the DataFrame:
0


In [28]:
df = pd.DataFrame(dataset)
label_counts = df['label'].value_counts()
num_unique_labels = df['label'].nunique()
print("\nNumber of Unique Labels:", num_unique_labels)


Number of Unique Labels: 22


In [29]:
for column in dataset.columns:
    if dataset[column].dtype == 'object' or pd.api.types.is_categorical_dtype(dataset[column]):
        print(f"\nUnique labels and their counts in the column '{column}':")
        print(dataset[column].value_counts(dropna=False)) 



Unique labels and their counts in the column 'label':
label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64


/var/folders/4b/8mh4jz7d46qf0m9j_bdwy1d40000gn/T/ipykernel_7672/2674492824.py:2: DeprecationWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if dataset[column].dtype == 'object' or pd.api.types.is_categorical_dtype(dataset[column]):


In [30]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y=label_encoder.fit_transform(y)

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [32]:
print(X_train)

[[ 27.         120.         200.         ...  90.74531921   6.11021883
  116.7036582 ]
 [ 81.          36.          38.         ...  87.98329901   6.33483786
  150.3166152 ]
 [ 90.          59.          35.         ...  89.86454053   7.09822793
  175.1742112 ]
 ...
 [ 35.          64.          15.         ...  63.53604453   6.50014496
   69.5274407 ]
 [ 39.          65.          23.         ...  69.12613376   7.6859593
   41.02682925]
 [ 14.          22.           9.         ...  91.13772765   6.54319181
  112.5090516 ]]


In [33]:
print(X_test)

[[105.          14.          50.         ...  87.6883982    6.41905219
   59.65590798]
 [ 91.          12.          46.         ...  85.49938185   6.34394252
   48.31219031]
 [ 14.         121.         203.         ...  83.74765639   6.15868941
   74.46411148]
 ...
 [117.          56.          15.         ...  77.0543546    7.36825823
   89.1188212 ]
 [ 27.          64.          21.         ...  68.68401492   7.54380422
   73.67166182]
 [ 31.         130.         198.         ...  92.73446667   5.55482356
  120.0586671 ]]


In [34]:
print(Y_train) 

[ 0  8  8 ...  2 10 16]


In [35]:
print(Y_test)

[21 21  7  3  2 20 13  9 15  1 13  5 10 14 12  0  5 10  5 12  4  2  9  8
  6  5 10 16 13  9 19 20 11 15  4  6 12 12 21 13 11  2 18 21 18 14  9  9
  6 14 13  2  0 15 18  1 17 12 10  6 16 14 21 20 15  0  7  5  0 16  4 19
  9 11  7 13  3 11  8 12 20  2 21 21 15  6 11 10 13 17  2  8 14  7 14 11
  5  8 10  3 16  8 14  1  1 20 21  5 18 15 15 12  5  7 16 19 14 10 11  8
 19 10 16  3  3  2 19 16  3 17 13 13 15 14 11 14  4 19 16  2  2  7  0  5
  3  0  8 12 21 17 16  4 13  1 19  3 21  2  0  8 10 18  8  9  9 15 20 15
  1 16 18  0 13  4  6 14  9 19 17 16 20 17 17 18  9  1  4 18 20 17 11  8
 13 20 11  5 18  4  3 12  4 19 11 13 13 16 15 11 18  1  3  2 18 16 13 14
 12 17 15 19 20 20  2 17  2  5 11  5 16 20 13 14 16  9 19  4 12 14  6 20
  3 14  0 18  2 20 21  2 19 16 11  7  3 18  8 17 19  5 12 13  8 21 19 20
  7  4  8 10  3  5  5 17 19 11 20  3 18 16 19 18  4  9 19 15 13 12 10  1
  2 12  9 12  6 14 17  7  7 18 17  8 20  3 15  5 21 20  8 17  7 15  2 13
 13  3  2 12  1 12 19  8 16 15  3 10  6 17  7  9 10

In [36]:

label_mapping = dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
print("Label Mapping:")
print(label_mapping)

Label Mapping:
{'apple': 0, 'banana': 1, 'blackgram': 2, 'chickpea': 3, 'coconut': 4, 'coffee': 5, 'cotton': 6, 'grapes': 7, 'jute': 8, 'kidneybeans': 9, 'lentil': 10, 'maize': 11, 'mango': 12, 'mothbeans': 13, 'mungbean': 14, 'muskmelon': 15, 'orange': 16, 'papaya': 17, 'pigeonpeas': 18, 'pomegranate': 19, 'rice': 20, 'watermelon': 21}


In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
print(X_train)

[[-0.64463185  2.00512125  2.96466347 ...  0.86301256 -0.4785779
   0.23692732]
 [ 0.81334894 -0.52889759 -0.2035231  ...  0.7381018  -0.18240887
   0.84590226]
 [ 1.05634574  0.1649409  -0.26219322 ...  0.82317986  0.82415091
   1.29625399]
 ...
 [-0.42863469  0.31577536 -0.65332736 ... -0.36751109  0.03555503
  -0.61777686]
 [-0.32063612  0.34594225 -0.4968737  ... -0.11470255  1.59909782
  -1.13413007]
 [-0.99562722 -0.95123406 -0.7706676  ...  0.880759    0.09231399
   0.1609325 ]]


In [39]:
print(X_test)

[[ 1.4613404  -1.19256918  0.03115739 ...  0.72476508 -0.07136897
  -0.79662206]
 [ 1.08334538 -1.25290297 -0.04706944 ...  0.62576809 -0.17040403
  -1.00213923]
 [-0.99562722  2.03528814  3.02333359 ...  0.54654732 -0.41466753
  -0.52833787]
 ...
 [ 1.78533613  0.07444023 -0.65332736 ...  0.24384664  1.18019647
  -0.26283457]
 [-0.64463185  0.31577536 -0.53598712 ... -0.13469712  1.41166076
  -0.54269489]
 [-0.53663327  2.30679015  2.92555005 ...  0.9529706  -1.21088837
   0.29771091]]


In [40]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=100,criterion="entropy",random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test,y_pred)
print(cm)

[[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [43]:
s=accuracy_score(Y_test,y_pred)
print(s)

0.9954545454545455


In [44]:
y2_pred = classifier.predict(X_test)
y2_pred

array([21, 21,  7,  3,  2, 20, 13,  9, 15,  1, 13,  5, 10, 14, 12,  0,  5,
       10,  5, 12,  4,  2,  9,  8,  6,  5, 10, 16, 13,  9, 19, 20, 11, 15,
        4,  6, 12, 12, 21,  2, 11,  2, 18, 21, 18, 14,  9,  9,  6, 14, 13,
        2,  0, 15, 18,  1, 17, 12, 10,  6, 16, 14, 21, 20, 15,  0,  7,  5,
        0, 16,  4, 19,  9, 11,  7, 13,  3, 11,  8, 12, 20,  2, 21, 21, 15,
        6, 11, 10, 13, 17,  2,  8, 14,  7, 14, 11,  5,  8, 10,  3, 16,  8,
       14,  1,  1, 20, 21,  5, 18, 15, 15, 12,  5,  7, 16, 19, 14, 10, 11,
        8, 19, 10, 16,  3,  3,  2, 19, 16,  3, 17, 13, 13, 15, 14, 11, 14,
        4, 19, 16,  2,  2,  7,  0,  5,  3,  0,  8, 12, 21, 17, 16,  4, 13,
        1, 19,  3, 21,  2,  0,  8, 10, 18,  8,  9,  9, 15, 20, 15,  1, 16,
       18,  0, 13,  4,  6, 14,  9, 19, 17, 16, 20, 17, 17, 18,  9,  1,  4,
       18, 20, 17, 11,  8, 13, 20, 11,  5, 18,  4,  3, 12,  4, 19, 11, 13,
       13, 16, 15, 11, 18,  1,  3,  2, 18, 16, 13, 14, 12, 17, 15, 19,  8,
       20,  2, 17,  2,  5

In [45]:
import pickle

# Save the model to a pickle file
with open('random_forest_model.pkl', 'wb') as file:
    pickle.dump(classifier, file)

print("Model exported to random_forest_model.pkl")

Model exported to random_forest_model.pkl


In [46]:
with open('random_forest_model.pkl', 'rb') as file:
    loaded_classifier = pickle.load(file)

y_pred_loaded = loaded_classifier.predict(X_test)


In [47]:
# Load the model from the pickle file
with open('random_forest_model.pkl', 'rb') as file:
    loaded_classifier = pickle.load(file)

# Example random values for N, P, K, temperature, humidity, ph, and rainfall
# Replace these with actual input values
random_input = np.array([[90, 42, 43, 20.5, 82.3, 6.5, 202]])

# You must use the same StandardScaler instance used during training (already fit on the training data)
# Assuming the scaler 'sc' from the previous code is still available and was used for training
random_input_scaled = sc.transform(random_input)

# Predict the label using the loaded model
predicted_label_encoded = loaded_classifier.predict(random_input_scaled)

# If you used a label encoder, map the numeric prediction back to the original labels
predicted_label = label_encoder.inverse_transform(predicted_label_encoded)

print("Predicted label:", predicted_label[0])

Predicted label: rice
